
# spring.application.name=bcy
spring:
    application:
        name: 'bcy'
    datasource:
        url: jdbc:mysql://107.182.184.150:3306/bcy
        username: root
        password: changhao123
        driver-class-name: 'com.mysql.cj.jdbc.Driver'

mybatis:
    mapper-locations: classpath:/mapper/*.xml
        
server:
    port: 8888
    servlet:
        encoding:
            charset: 'UTF-8'
            enabled: true
            force: true
