on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          databaseurl: ${{ secrets.databaseurl }}
          databaseuser: ${{ secrets.databaseuser }}
          databasepwd: ${{ secrets.databasepwd }}
      - run: |
          ls
          node setup.js
          cat ./src/main/resources/application.yml
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          java --version
      - name: java package
        run: |
          mvn clean package
          cd target
          ls
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "target"
      - name: Build Image
        env:
          DockerUsername: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DockerUsername -p $DockerPassword
          docker build -t yisar/bcy_api .
          docker push yisar/bcy_api
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker-compose pull 
            docker-compose up -d 